# Generated by Django 5.2.3 on 2025-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('car_class', models.CharField(choices=[('econom', 'Econom'), ('comfort', 'Comfort'), ('business', 'Business')], max_length=10)),
                ('fuel_level', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20)),
                ('tariff', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
