# Generated by Django 5.2.3 on 2025-06-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='longitude',
        ),
    ]
