# Generated by Django 5.1 on 2025-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='car',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес')], default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='number_plate',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
